//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.13 at 06:13:13 PM YEKT 
//


package com.github.trickster88.clients.openweathermap.dto;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.trickster88.clients.openweathermap.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Current_QNAME = new QName("current-weather", "current");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.trickster88.clients.openweathermap.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CurrentWeather }
     * 
     */
    public CurrentWeather createCurrentWeather() {
        return new CurrentWeather();
    }

    /**
     * Create an instance of {@link Clouds }
     * 
     */
    public Clouds createClouds() {
        return new Clouds();
    }

    /**
     * Create an instance of {@link Wind }
     * 
     */
    public Wind createWind() {
        return new Wind();
    }

    /**
     * Create an instance of {@link Pressure }
     * 
     */
    public Pressure createPressure() {
        return new Pressure();
    }

    /**
     * Create an instance of {@link Speed }
     * 
     */
    public Speed createSpeed() {
        return new Speed();
    }

    /**
     * Create an instance of {@link LastUpdate }
     * 
     */
    public LastUpdate createLastUpdate() {
        return new LastUpdate();
    }

    /**
     * Create an instance of {@link Direction }
     * 
     */
    public Direction createDirection() {
        return new Direction();
    }

    /**
     * Create an instance of {@link Sun }
     * 
     */
    public Sun createSun() {
        return new Sun();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link Temperature }
     * 
     */
    public Temperature createTemperature() {
        return new Temperature();
    }

    /**
     * Create an instance of {@link Coord }
     * 
     */
    public Coord createCoord() {
        return new Coord();
    }

    /**
     * Create an instance of {@link Humidity }
     * 
     */
    public Humidity createHumidity() {
        return new Humidity();
    }

    /**
     * Create an instance of {@link Precipitation }
     * 
     */
    public Precipitation createPrecipitation() {
        return new Precipitation();
    }

    /**
     * Create an instance of {@link Weather }
     * 
     */
    public Weather createWeather() {
        return new Weather();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurrentWeather }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "current-weather", name = "current")
    public JAXBElement<CurrentWeather> createCurrent(CurrentWeather value) {
        return new JAXBElement<CurrentWeather>(_Current_QNAME, CurrentWeather.class, null, value);
    }

}
